@TIK.Backend_HostAddress = http://localhost:5268

GET {{TIK.Backend_HostAddress}}/weatherforecast/
Accept: application/json

###


GET {{TIK.Backend_HostAddress}}/secret

###

GET {{TIK.Backend_HostAddress}}/api/examples/getExample1

###

GET {{TIK.Backend_HostAddress}}/api/examples/getExample2

###
